---
- ros_topic_name: "/clock"
  gz_topic_name: "/world/ramp_world/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "imu"
  gz_topic_name: "/wcr/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "camera"
  gz_topic_name: "/wcr/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "camera_info"
  gz_topic_name: "/wcr/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "optical_flow/image_raw"
  gz_topic_name: "/wcr/optical_flow/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "optical_flow/camera_info"
  gz_topic_name: "/wcr/optical_flow/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "distance"
  gz_topic_name: "/wcr/distance"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "pressure"
  gz_topic_name: "/wcr/pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "ignition.msgs.FluidPressure"
  direction: GZ_TO_ROS